version: '3.1'
services:
  db:
    image: postgres
    restart: always
    env_file:
    - config.properties
  websoc-server:
    environment:
      spring.profiles.active: dev
      spring.datasource.url: jdbc:postgresql://db:5432/ftp_server
      spring.datasource.username: postgres
      spring.datasource.password: ribamech
    restart: always
    build: .
    ports:
    - "8443:8443"
