version: '3.1'
services:
  db:
    image: postgres
    restart: unless-stopped
    restart: always
    environment:
      POSTGRES_PASSWORD: ribamech
      POSTGRES_DB: ftp_server
  websoc-server:
    image: ftp-websocket-server:latest
    restart: unless-stopped
    environment:
      spring.profiles.active: dev
      spring.datasource.url: jdbc:postgresql://db:5432/ftp_server
      spring.datasource.username: postgres
      spring.datasource.password: ribamech
    restart: always
    build: .
    ports:
    - "8443:8443"
